### ISSUE TITLE
Only build metadata payload NDJSON string once

### ISSUE THREAD

**Issue by watson** [elastic/apm-nodejs-http-client#35]
Only stringify the `metadata` object once and reuse the generated string for all future metadata events being sent.

**Comment by alemagio** [comment]
Hi, i would like to work on this.
Tell me if i understood the problem:
- In the _encode function of the Client.prototype we serialize the entire output
- what we want is to save the serialized metadata and reuse it instead of doing the serialization every time.
Correct?

**Comment by Qard** [comment]
Yeah, what I would do is store the encoded version on the client and just change [this line](https://github.com/elastic/apm-nodejs-http-client/blob/master/index.js#L494) to write the already encoded content rather than redoing the encoding every time. You'll want to make sure the pre-encoded metadata is rebuilt any time the config changes though--the end of `Client.prototype.config` is probably a good place to generate and store the pre-encoded metadata header.
